# Generated by Django 5.0.4 on 2024-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_Project', models.CharField(max_length=100, verbose_name='项目编号')),
                ('NAME_Project', models.CharField(max_length=100, verbose_name='项目名称')),
                ('TYPE_Project', models.CharField(max_length=100, verbose_name='项目类型')),
                ('VALUE_Project', models.IntegerField(default=0, verbose_name='项目价值')),
                ('START_Project', models.DateField(verbose_name='项目开始时间')),
                ('END_Project', models.DateField(verbose_name='项目结束时间')),
                ('ADDRESS_Project', models.CharField(max_length=100, verbose_name='项目地址')),
                ('DESC_Project', models.CharField(max_length=1000, verbose_name='项目描述')),
            ],
        ),
    ]
